name: iOS App build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  projectName: hspInputTest

jobs:
  build:
    name: Build .app and Convert to .ipa
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          cd $projectName
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]") 
          echo "SCHEME=$default" >> $GITHUB_ENV
          echo Using default scheme: $default

      - name: Build .app (Simulator)
        run: |
          cd $projectName
          xcodebuild -scheme "$SCHEME" -sdk iphoneos -configuration Release build CODE_SIGNING_ALLOWED=NO

      - name: Find .app Path
        run: |
          cd $projectName
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV

      - name: Convert .app to .ipa
        run: |
          mkdir -p Payload
          cp -R "${{ env.APP_PATH }}" Payload/
          zip -r ${{env.projectName}}.ipa Payload

      - name: Upload .ipa as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.projectName}}
          path: ${{env.projectName}}.ipa
